#!/usr/bin/env python3
"""Part 4: Add 150+ latest 2025-2026 current affairs questions across ALL sections.
Covers: HP news, India events, horticulture developments, schemes, budget, and more."""
import json, os
BASE = os.path.dirname(os.path.abspath(__file__))

def append_questions(filepath, new_qs):
    with open(filepath, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    existing.extend(new_qs)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=4, ensure_ascii=False)
    print(f"  {os.path.basename(filepath)}: added {len(new_qs)}, total now {len(existing)}")

# ========================================================
# 1. CURRENT AFFAIRS — Latest 2025-2026 (30 questions)
# ========================================================
current_affairs_2026 = [
    {"id":"CA_041","question":"Union Budget 2026-27 projects India's GDP growth in FY26 at:","options":["6.5%","7.0%","7.4%","8.0%"],"answer":2,"explanation":"Union Budget 2026-27 projected India's economic growth at 7.4% in FY26 and 6.8-7.2% in FY27.","difficulty":"medium","topic":"current_affairs","source":"Union_Budget_2026"},
    {"id":"CA_042","question":"PM Dhan-Dhaanya Krishi Yojana launched in 2025 covers how many districts?","options":["50","75","100","150"],"answer":2,"explanation":"PM Dhan-Dhaanya Krishi Yojana (PM DDKY) launched in October 2025 covers 100 districts to enhance agricultural productivity and crop diversification.","difficulty":"medium","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_043","question":"How many Padma Awards were conferred in 2026?","options":["100","115","131","150"],"answer":2,"explanation":"President approved 131 Padma Awards for 2026: 5 Padma Vibhushan, 13 Padma Bhushan, and 113 Padma Shri.","difficulty":"medium","topic":"current_affairs","source":"GOI_2026"},
    {"id":"CA_044","question":"The total expenditure in Union Budget 2025-26 is approximately:","options":["₹40.65 lakh crore","₹45.65 lakh crore","₹50.65 lakh crore","₹55.65 lakh crore"],"answer":2,"explanation":"Total expenditure in Union Budget 2025-26 is ₹50.65 lakh crore with total receipts (excluding borrowings) at ₹34.96 lakh crore.","difficulty":"hard","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_045","question":"The fiscal deficit target for FY 2025-26 is:","options":["3.5% of GDP","4.0% of GDP","4.4% of GDP","5.0% of GDP"],"answer":2,"explanation":"Fiscal deficit for 2025-26 is estimated at 4.4% of GDP.","difficulty":"hard","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_046","question":"National Education Policy (NEP) introduces which school structure?","options":["10+2 system","8+4 system","5+3+3+4 system","6+3+3 system"],"answer":2,"explanation":"NEP introduces 5+3+3+4 (Foundational+Preparatory+Middle+Secondary) replacing the older 10+2 system.","difficulty":"easy","topic":"current_affairs","source":"NEP_2025"},
    {"id":"CA_047","question":"Urban Challenge Fund announced in Budget 2025-26 has an outlay of:","options":["₹50,000 crore","₹75,000 crore","₹1 lakh crore","₹1.5 lakh crore"],"answer":2,"explanation":"Urban Challenge Fund of ₹1 lakh crore was announced for 'Cities as Growth Hubs' with ₹10,000 crore allocated for 2025-26.","difficulty":"hard","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_048","question":"Capital expenditure earmarked for FY 2025-26 is:","options":["₹9.21 lakh crore","₹10.21 lakh crore","₹11.21 lakh crore","₹12.21 lakh crore"],"answer":2,"explanation":"Capital expenditure of ₹11.21 lakh crore (3.1% of GDP) was earmarked for FY2025-26.","difficulty":"hard","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_049","question":"Makhana Board was proposed to be established in which state?","options":["West Bengal","Odisha","Bihar","Assam"],"answer":2,"explanation":"Government proposed to establish a Makhana Board in Bihar to boost makhana (fox nut) production and marketing.","difficulty":"medium","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_050","question":"Wings India 2026, Asia's largest civil aviation event, was held at:","options":["Delhi","Mumbai","Hyderabad","Bengaluru"],"answer":2,"explanation":"Wings India 2026 was held at Begumpet Airport, Hyderabad from January 28-31, 2026.","difficulty":"medium","topic":"current_affairs","source":"Events_2026"},
    {"id":"CA_051","question":"India Energy Week 2026 was held in:","options":["Delhi","Mumbai","Goa","Chennai"],"answer":2,"explanation":"India Energy Week 2026, focusing on sustainable global energy transition, took place from Jan 27-30, 2026, in Goa.","difficulty":"medium","topic":"current_affairs","source":"Events_2026"},
    {"id":"CA_052","question":"India's total horticulture production in 2024-25 is estimated at:","options":["320 MT","345 MT","369 MT","390 MT"],"answer":2,"explanation":"India's horticulture production for 2024-25 is estimated at 369.05 million tonnes, a 4% increase from the previous year.","difficulty":"medium","topic":"current_affairs","source":"Horticulture_2025"},
    {"id":"CA_053","question":"'Bharatiya Bhasha Pustak Scheme' aims at:","options":["Building roads","Promoting books in Indian languages","Import of foreign books","Digital payments"],"answer":1,"explanation":"Bharatiya Bhasha Pustak Scheme was proposed in Union Budget 2025-26 to promote publishing in Indian languages.","difficulty":"easy","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_054","question":"How many new labour codes came into effect in India?","options":["2","3","4","5"],"answer":2,"explanation":"Four new labour codes covering wages, social security, industrial relations, and occupational safety replaced old laws.","difficulty":"medium","topic":"current_affairs","source":"Labour_Reform_2025"},
    {"id":"CA_055","question":"'Aatmanirbharta in Pulses' scheme focuses on:","options":["Wheat production","Self-sufficiency in pulses like tur, urad, masoor","Sugarcane cultivation","Rice export"],"answer":1,"explanation":"Aatmanirbharta in Pulses scheme focuses on achieving self-sufficiency in specific legumes like tur (arhar), urad, and masoor.","difficulty":"medium","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_056","question":"India's fruit production in 2024-25 is projected to grow by:","options":["2.5%","3.8%","5.12%","7.5%"],"answer":2,"explanation":"Fruit production projected to grow by 5.12% to 118.76 million tonnes in 2024-25.","difficulty":"hard","topic":"current_affairs","source":"Horticulture_2025"},
    {"id":"CA_057","question":"Clean Plant Programme under horticulture aims at:","options":["Cleaning nurseries","Providing disease-free quality planting material","Pest control only","Organic certification"],"answer":1,"explanation":"Clean Plant Programme is a central sector scheme focused on providing high-quality, disease-free planting material.","difficulty":"medium","topic":"current_affairs","source":"MIDH_2025"},
    {"id":"CA_058","question":"MIDH was restructured in 2025 with revised guidelines. What is a key change?","options":["Coverage reduced to 10 states","Cost norms unchanged","Extended coverage to all districts, enhanced cost norms","Only for North-East states"],"answer":2,"explanation":"MIDH 2025 restructuring extends coverage to all districts, enhances cost norms, and promotes high-value and exotic crops.","difficulty":"hard","topic":"current_affairs","source":"MIDH_2025"},
    {"id":"CA_059","question":"Horticulture Cluster Development Programme (CDP) promotes:","options":["Single-crop farming","Integrated and market-led cluster development","Deforestation","Chemical farming only"],"answer":1,"explanation":"CDP aims at integrated and market-led development of horticulture clusters including logistics, branding, and post-harvest management.","difficulty":"medium","topic":"current_affairs","source":"MIDH_2025"},
    {"id":"CA_060","question":"CHAMAN programme uses which technology for horticulture assessment?","options":["X-ray imaging","Geo-informatics and remote sensing","Radio waves","Manual counting"],"answer":1,"explanation":"CHAMAN (Coordinated Programme on Horticulture Assessment and Management using Geo-informatics) uses remote sensing for digital inventory.","difficulty":"medium","topic":"current_affairs","source":"MIDH_2025"},
    {"id":"CA_061","question":"Market Intervention Scheme (MIS) in 2025 added which new component?","options":["Export ban","Price Differential Payment (PDP)","Import subsidy","Free seeds"],"answer":1,"explanation":"MIS 2025 added Price Differential Payment (PDP) and reimbursement for transport/storage of Tomato, Onion, Potato (TOP) crops.","difficulty":"hard","topic":"current_affairs","source":"MIDH_2025"},
    {"id":"CA_062","question":"India's vegetable production in 2024-25 is expected to increase by:","options":["2.0%","4.09%","6.5%","8.0%"],"answer":1,"explanation":"Vegetable output expected to increase by 4.09% to 215.68 million tonnes in 2024-25.","difficulty":"hard","topic":"current_affairs","source":"Horticulture_2025"},
    {"id":"CA_063","question":"Under MIDH, what is the Central share for North-Eastern & Himalayan states?","options":["50%","60%","75%","90%"],"answer":3,"explanation":"For NE and Himalayan states, Government of India contributes 90% of MIDH outlay; for others, 60% centre and 40% state.","difficulty":"medium","topic":"current_affairs","source":"MIDH_2025"},
    {"id":"CA_064","question":"Saksham Anganwadi and Poshan 2.0 programme provides nutritional support to:","options":["Only children","Only senior citizens","Children, lactating mothers, pregnant women, and adolescent girls","Only farmers"],"answer":2,"explanation":"Saksham Anganwadi and Poshan 2.0 provides nutritional support to children, lactating mothers, pregnant women, and adolescent girls.","difficulty":"easy","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_065","question":"'Rural Prosperity and Resilience Programme' initially covers how many agri-districts?","options":["50","75","100","200"],"answer":2,"explanation":"Rural Prosperity and Resilience Programme initially covers 100 agri-districts to address under-employment through skilling and investment.","difficulty":"medium","topic":"current_affairs","source":"Union_Budget_2025"},
    {"id":"CA_066","question":"India's rank in vegetable production globally is:","options":["1st","2nd","3rd","4th"],"answer":1,"explanation":"India is the 2nd largest vegetable producer globally after China.","difficulty":"easy","topic":"current_affairs","source":"Horticulture_2025"},
    {"id":"CA_067","question":"Which award recognizes states for best performance in horticulture at the Agriculture Leadership Conclave?","options":["Padma Award","Agriculture Leadership Award","Bharat Ratna","National Horticulture Award"],"answer":1,"explanation":"Agriculture Leadership Award was given to Nagaland as best state in horticulture at the 15th Agriculture Leadership Conclave 2024.","difficulty":"medium","topic":"current_affairs","source":"Awards_2024"},
    {"id":"CA_068","question":"Horticulture's contribution to agricultural GVA is approximately:","options":["10%","20%","33% (one-third)","50%"],"answer":2,"explanation":"Horticulture contributes nearly one-third (33%) of India's agricultural Gross Value Added (GVA).","difficulty":"medium","topic":"current_affairs","source":"Horticulture_2025"},
    {"id":"CA_069","question":"Union Budget 2026-27 was presented on:","options":["1 January 2026","1 February 2026","15 March 2026","1 April 2026"],"answer":1,"explanation":"Union Budget 2026-27 was presented on 1 February 2026 by the Finance Minister.","difficulty":"easy","topic":"current_affairs","source":"Union_Budget_2026"},
    {"id":"CA_070","question":"'Scheme for First-time Entrepreneurs' was proposed in which Budget?","options":["2023-24","2024-25","2025-26","2026-27"],"answer":2,"explanation":"Scheme for First-time Entrepreneurs was proposed in Union Budget 2025-26 to support new business owners.","difficulty":"medium","topic":"current_affairs","source":"Union_Budget_2025"},
]

# ========================================================
# 2. HP GK — Latest 2025-2026 HP News & Schemes (30 questions)
# ========================================================
hp_gk_2026 = [
    {"id":"HPGK_046","question":"HP Budget 2025-26 total outlay presented by CM Sukhvinder Singh Sukhu is:","options":["₹45,000 crore","₹52,000 crore","₹58,514 crore","₹65,000 crore"],"answer":2,"explanation":"CM Sukhu presented a tax-free HP Budget 2025-26 with total outlay of ₹58,514 crore on 17 March 2025.","difficulty":"hard","topic":"hp_gk","source":"HP_Budget_2025"},
    {"id":"HPGK_047","question":"HP's projected GSDP for 2025-26 is approximately:","options":["₹1,80,000 crore","₹2,20,000 crore","₹2,55,636 crore","₹3,00,000 crore"],"answer":2,"explanation":"HP's projected GSDP for 2025-26 is ₹2,55,636 crore, a 10% growth over 2024-25.","difficulty":"hard","topic":"hp_gk","source":"HP_Budget_2025"},
    {"id":"HPGK_048","question":"HP Shiva Project (Subtropical Horticulture, Irrigation and Value Addition Project) outlay is:","options":["₹500 crore","₹800 crore","₹1,292 crore","₹1,500 crore"],"answer":2,"explanation":"HP SHIVA Project with ₹1,292 crore outlay aims to enhance horticulture across seven districts.","difficulty":"hard","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_049","question":"HP SHIVA Project covers how many districts?","options":["3","5","7","10"],"answer":2,"explanation":"HP SHIVA Project covers seven districts for subtropical horticulture, irrigation and value addition.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_050","question":"Him Bhog Atta Initiative in HP sources maize flour from:","options":["Chemical farming","Imported grain","Organic maize through natural farming","Hybrid wheat"],"answer":2,"explanation":"Him Bhog Atta Initiative supports natural farming by sourcing maize flour from organically grown maize.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_051","question":"The World Bank approved how much funding for HP in 2026 for disaster management?","options":["$100 million","$150 million","$245 million","$300 million"],"answer":2,"explanation":"On 10 Feb 2026, World Bank approved $245 million for HP to manage extreme weather events and rebuild resilient infrastructure.","difficulty":"hard","topic":"hp_gk","source":"HP_2026"},
    {"id":"HPGK_052","question":"Rajiv Gandhi Prakritik Kheti Start-up Yojana in HP promotes:","options":["Chemical farming","Natural farming practices","Fish farming","Poultry farming"],"answer":1,"explanation":"This scheme promotes natural farming practices in Himachal Pradesh.","difficulty":"easy","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_053","question":"HP Organic Compost Scheme purchases organic/vermicompost at:","options":["₹100/quintal","₹200/quintal","₹300/quintal","₹500/quintal"],"answer":2,"explanation":"HP Organic Compost Scheme purchases organic and vermicompost at ₹300 per quintal to aid small farmers.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_054","question":"HP Budget 2025-26 plans to bring how many additional farmers under natural farming?","options":["25,000","50,000","1 lakh","2 lakh"],"answer":2,"explanation":"HP Budget 2025-26 plans to bring an additional 1 lakh farmers under natural farming practices.","difficulty":"medium","topic":"hp_gk","source":"HP_Budget_2025"},
    {"id":"HPGK_055","question":"Spice Park announced in HP Budget 2025-26 will be established in:","options":["Shimla","Mandi","Hamirpur","Kullu"],"answer":2,"explanation":"A Spice Park in Hamirpur was announced in HP Budget 2025-26 for spice processing and value addition.","difficulty":"medium","topic":"hp_gk","source":"HP_Budget_2025"},
    {"id":"HPGK_056","question":"The Chief Minister Tourism Start-Up Scheme in HP has an outlay of:","options":["₹20 crore","₹35 crore","₹50 crore","₹75 crore"],"answer":2,"explanation":"CM Tourism Start-Up Scheme offers interest subvention of 4-5% on loans for homestays/hotels with ₹50 crore outlay.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_057","question":"Indira Gandhi Sukh Suraksha Yojana deposits how much when a girl child is born in BPL family?","options":["₹10,000","₹15,000","₹25,000","₹50,000"],"answer":2,"explanation":"₹25,000 is deposited in an insurance company when a girl child is born in a BPL family under this scheme.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_058","question":"HP Sahara Yojana provides monthly assistance of how much to patients with serious diseases?","options":["₹1,000","₹2,000","₹3,000","₹5,000"],"answer":2,"explanation":"HP Sahara Yojana provides ₹3,000/month to economically weaker patients suffering from cancer, Parkinson's, paralysis etc.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_059","question":"Under Him Unnati Yojana, the focus is on:","options":["Mining development","Overall agriculture development","Tourism only","Industrial growth only"],"answer":1,"explanation":"Him Unnati Yojana (also called Him Krishi Yojana) is for overall development of agriculture in HP.","difficulty":"easy","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_060","question":"In HP Budget 2025-26, cow milk price was increased from ₹45 to:","options":["₹48/litre","₹50/litre","₹51/litre","₹55/litre"],"answer":2,"explanation":"Cow milk price increased from ₹45 to ₹51/litre and buffalo milk from ₹55 to ₹61/litre in HP Budget 2025-26.","difficulty":"medium","topic":"hp_gk","source":"HP_Budget_2025"},
    {"id":"HPGK_061","question":"HP Budget 2025-26 planned procurement of how many new electric buses?","options":["100","250","500","1000"],"answer":2,"explanation":"HP Budget 2025-26 plans procurement of 500 new electric buses.","difficulty":"medium","topic":"hp_gk","source":"HP_Budget_2025"},
    {"id":"HPGK_062","question":"Who is the current CM of Himachal Pradesh (2025-26)?","options":["Jai Ram Thakur","Virbhadra Singh","Sukhvinder Singh Sukhu","Pratibha Singh"],"answer":2,"explanation":"Sukhvinder Singh Sukhu has been CM of HP since 11 December 2022.","difficulty":"easy","topic":"hp_gk","source":"HP_2025"},
    {"id":"HPGK_063","question":"The HP Special Relief Package for Disaster-Hit Families provides housing aid up to:","options":["₹3 lakh","₹5 lakh","₹7 lakh","₹10 lakh"],"answer":2,"explanation":"HP Special Relief Package (approved July 28, 2025) provides financial support ranging from ₹50,000 to ₹7 lakh for damaged houses.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_064","question":"HP Agriculture Loan Interest Subvention Scheme covers loans up to:","options":["₹1 lakh","₹2 lakh","₹3 lakh","₹5 lakh"],"answer":2,"explanation":"State bears 50% of accrued interest for agricultural loans up to ₹3 lakh under this one-time settlement scheme.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_065","question":"HP Dev Bhoomi Darshan Yojana provides how much bus fare discount for citizens aged 70-80?","options":["25%","50%","75%","100%"],"answer":1,"explanation":"50% discount for 70-80 years and 100% discount for above 80 years on bus fares to holy places.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_066","question":"Who is the current Governor of Himachal Pradesh (2025-26)?","options":["Bandaru Dattatreya","Rajendra Arlekar","Shiv Pratap Shukla","Kalraj Mishra"],"answer":2,"explanation":"Shiv Pratap Shukla serves as the Governor of HP in 2025-26 and conferred Teachers' Day Awards in 2025.","difficulty":"medium","topic":"hp_gk","source":"HP_2025"},
    {"id":"HPGK_067","question":"Krishak Bakri Palan Yojana in HP aims at:","options":["Fish farming","Goat rearing for income generation and meat production","Cattle breeding","Poultry farming"],"answer":1,"explanation":"Krishak Bakri Palan Yojana boosts income for economically weaker segments through goat rearing and meat production.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_068","question":"Kullu Dussehra 2025 was celebrated from:","options":["1-7 October","10-16 October","15-21 October","20-27 October"],"answer":0,"explanation":"Kullu Dussehra 2025 was celebrated from October 1-7, 2025.","difficulty":"easy","topic":"hp_gk","source":"HP_Events_2025"},
    {"id":"HPGK_069","question":"HP Mukhyamantri Awas Yojana (HPBOCWWB) provides housing aid of:","options":["₹50,000","₹1,00,000","₹1,50,000","₹2,00,000"],"answer":2,"explanation":"₹1,50,000 financial assistance for housing is provided to registered building and construction workers.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_070","question":"HP fiscal deficit target for 2025-26 is what percentage of GSDP?","options":["3%","3.5%","4%","4.5%"],"answer":2,"explanation":"HP targeted fiscal deficit of 4% of GSDP, amounting to ₹10,338 crore for 2025-26.","difficulty":"hard","topic":"hp_gk","source":"HP_Budget_2025"},
    {"id":"HPGK_071","question":"Indira Gandhi Pyari Behna Sukh-Samman Nidhi Yojana provides:","options":["Free education","Monthly assistance to women","Free housing","Crop insurance"],"answer":1,"explanation":"This HP scheme provides monthly financial assistance to women in the state.","difficulty":"easy","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_072","question":"HP Electric Taxi Subsidy Programme under Rajiv Gandhi Self-Employment Start-up Scheme provides:","options":["25% subsidy","40% subsidy","50% subsidy","75% subsidy"],"answer":2,"explanation":"50% subsidy is provided for purchasing e-taxis under this programme (from FY 2023).","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2023"},
    {"id":"HPGK_073","question":"Swami Vivekananda Utkrisht Chhatravriti Yojna in HP provides scholarship of:","options":["₹10,000/year","₹15,000/year","₹18,000/year","₹25,000/year"],"answer":2,"explanation":"₹18,000/year scholarship for general category students after matriculation in HP.","difficulty":"medium","topic":"hp_gk","source":"HP_Scheme_2025"},
    {"id":"HPGK_074","question":"Himachal Pradesh Assembly in Feb 2026 extended the term of mayor/deputy mayor to:","options":["3 years","4 years","5 years","6 years"],"answer":2,"explanation":"HP Municipal Corporation Amendment Bill 2025 extends the term of office for mayor and deputy mayor to five years.","difficulty":"medium","topic":"hp_gk","source":"HP_2026"},
    {"id":"HPGK_075","question":"Mandi Shivratri 2026 is planned for:","options":["25 Feb - 2 Mar","15-21 February","1-7 March","10-16 March"],"answer":1,"explanation":"Mandi Shivratri 2026 is planned for February 15-21, 2026.","difficulty":"easy","topic":"hp_gk","source":"HP_Events_2026"},
]

# ========================================================
# 3. GENERAL HORTICULTURE — Latest 2025-2026 Developments (15 questions)
# ========================================================
gen_hort_2026 = [
    {"id":"GH_061","question":"India's horticulture production in 2024-25 grew by approximately:","options":["1%","2%","4%","6%"],"answer":2,"explanation":"Overall horticulture production estimated at 369.05 MT in 2024-25, a 4% increase from the previous year.","difficulty":"medium","topic":"general_horticulture","source":"Horticulture_2025"},
    {"id":"GH_062","question":"MIDH was introduced as a centrally sponsored scheme in:","options":["2010-11","2012-13","2014-15","2016-17"],"answer":2,"explanation":"MIDH was introduced in 2014-15 to foster holistic growth of the horticulture sector, subsuming NHM.","difficulty":"medium","topic":"general_horticulture","source":"MIDH_2025"},
    {"id":"GH_063","question":"Under MIDH 2025 restructuring, coverage has been extended to:","options":["Only NE states","Only Himalayan states","All districts across the country","Only 100 districts"],"answer":2,"explanation":"MIDH 2025 revised guidelines extend coverage to all districts, enhancing cost norms and promoting high-value crops.","difficulty":"medium","topic":"general_horticulture","source":"MIDH_2025"},
    {"id":"GH_064","question":"NHM was initially launched in:","options":["2000-01","2003-04","2005-06","2008-09"],"answer":2,"explanation":"National Horticulture Mission was launched in 2005-06 and later subsumed under MIDH in 2014-15.","difficulty":"medium","topic":"general_horticulture","source":"NHM"},
    {"id":"GH_065","question":"Horticulture Cluster Development Programme (CDP) focuses on:","options":["Single crop monoculture","Integrated market-led cluster development with branding and logistics","Only organic farming","Forest plantation"],"answer":1,"explanation":"CDP aims for integrated and market-led development of horticulture clusters with logistics, branding, and post-harvest management.","difficulty":"medium","topic":"general_horticulture","source":"CDP_2025"},
    {"id":"GH_066","question":"Clean Plant Programme is a:","options":["State sector scheme","Central sector scheme","Private scheme","NGO initiative"],"answer":1,"explanation":"Clean Plant Programme is a central sector scheme providing disease-free quality planting material for horticulture.","difficulty":"medium","topic":"general_horticulture","source":"MIDH_2025"},
    {"id":"GH_067","question":"India's fruit production in 2024-25 is estimated at approximately:","options":["95 MT","105 MT","118.76 MT","130 MT"],"answer":2,"explanation":"Fruit production projected at 118.76 million tonnes in 2024-25, growing by 5.12%.","difficulty":"hard","topic":"general_horticulture","source":"Horticulture_2025"},
    {"id":"GH_068","question":"CHAMAN stands for:","options":["Central Horticulture Assessment and Marketing Agency Network","Coordinated Programme on Horticulture Assessment and Management using Geo-informatics","Council of Horticulture And Modern Agriculture Network","Centre for Horticulture Analysis and Monitoring"],"answer":1,"explanation":"CHAMAN uses geo-spatial studies and remote sensing for digital mapping of horticultural zones.","difficulty":"hard","topic":"general_horticulture","source":"MIDH_2025"},
    {"id":"GH_069","question":"Market Intervention Scheme (MIS) 2025 added Price Differential Payment for which crops?","options":["Only rice and wheat","Only pulses","Tomato, Onion, Potato (TOP)","Only fruits"],"answer":2,"explanation":"MIS 2025 added PDP with transport/storage reimbursement specifically for TOP (Tomato, Onion, Potato) crops.","difficulty":"hard","topic":"general_horticulture","source":"MIDH_2025"},
    {"id":"GH_070","question":"India's vegetable production in 2024-25 is estimated at:","options":["180 MT","195 MT","215.68 MT","230 MT"],"answer":2,"explanation":"Vegetable output expected to increase by 4.09% to 215.68 million tonnes in 2024-25.","difficulty":"hard","topic":"general_horticulture","source":"Horticulture_2025"},
    {"id":"GH_071","question":"For MIDH, what is the Centre:State sharing pattern for general states?","options":["50:50","60:40","75:25","90:10"],"answer":1,"explanation":"For general states, MIDH follows 60:40 (Centre:State) sharing; for NE/Himalayan states, it is 90:10.","difficulty":"medium","topic":"general_horticulture","source":"MIDH_2025"},
    {"id":"GH_072","question":"NHB (National Horticulture Board) was established in:","options":["1980","1984","1988","1992"],"answer":1,"explanation":"NHB was established in 1984 under the Ministry of Agriculture for development and promotion of horticulture.","difficulty":"medium","topic":"general_horticulture","source":"NHB"},
    {"id":"GH_073","question":"Under CDP 2025, mega horticulture cluster projects focus on:","options":["Only domestic sales","Export competitiveness, branding, post-harvest, logistics","Reducing production","Chemical inputs only"],"answer":1,"explanation":"CDP mega cluster projects aim to boost global competitiveness through branding, logistics, and post-harvest management.","difficulty":"medium","topic":"general_horticulture","source":"CDP_2025"},
    {"id":"GH_074","question":"Which state received the 'Best State in Horticulture' award at 15th Agriculture Leadership Conclave?","options":["Himachal Pradesh","Maharashtra","Nagaland","Kerala"],"answer":2,"explanation":"Nagaland was recognized as best state in Horticulture at the 15th Agriculture Leadership Conclave 2024.","difficulty":"medium","topic":"general_horticulture","source":"Awards_2024"},
    {"id":"GH_075","question":"Horticulture sector covers which of these crops under MIDH?","options":["Only fruits and vegetables","Fruits, vegetables, spices, flowers only","Fruits, vegetables, spices, flowers, coconut, cashew, cocoa, bamboo, mushrooms, aromatic plants","Only cereals and pulses"],"answer":2,"explanation":"MIDH covers fruits, vegetables, root/tuber crops, mushrooms, spices, flowers, aromatic plants, coconut, cashew, cocoa, and bamboo.","difficulty":"medium","topic":"general_horticulture","source":"MIDH_2025"},
]

# ========================================================
# 4. POLITICAL SCIENCE — Latest 2025-2026 (10 questions)
# ========================================================
polsci_2026 = [
    {"id":"POL_041","question":"Which Constitutional Amendment introduced GST in India?","options":["99th Amendment","100th Amendment","101st Amendment","102nd Amendment"],"answer":2,"explanation":"101st Constitutional Amendment Act 2016 introduced GST, which was launched on 1 July 2017.","difficulty":"medium","topic":"political_science","source":"Indian_Constitution"},
    {"id":"POL_042","question":"The 106th Constitutional Amendment Act 2023 relates to:","options":["GST reform","Women's reservation in Parliament and State legislatures","Farm laws repeal","Education reform"],"answer":1,"explanation":"106th Amendment Act (Nari Shakti Vandan Adhiniyam) 2023 provides 33% reservation for women in Lok Sabha and State Assemblies.","difficulty":"hard","topic":"political_science","source":"Indian_Constitution"},
    {"id":"POL_043","question":"India is currently following which Five-Year Plan?","options":["12th Five-Year Plan","13th Five-Year Plan","Five-Year Plans discontinued, NITI Aayog replaced Planning Commission","14th Five-Year Plan"],"answer":2,"explanation":"Five-Year Plans were discontinued after the 12th plan (2012-17). NITI Aayog replaced Planning Commission in 2015.","difficulty":"medium","topic":"political_science","source":"Indian_Polity"},
    {"id":"POL_044","question":"16th Finance Commission was constituted under the chairmanship of:","options":["Y.V. Reddy","N.K. Singh","Arvind Panagariya","Urjit Patel"],"answer":2,"explanation":"16th Finance Commission was constituted in 2024 under the chairmanship of Dr. Arvind Panagariya for the period 2026-31.","difficulty":"hard","topic":"political_science","source":"Finance_Commission_2024"},
    {"id":"POL_045","question":"One Nation One Election Bill was passed in Lok Sabha in:","options":["2023","2024","2025","Not passed yet"],"answer":2,"explanation":"The Constitution (129th Amendment) Bill for simultaneous elections was passed in Lok Sabha in 2025 and referred to a JPC.","difficulty":"hard","topic":"political_science","source":"Indian_Polity_2025"},
    {"id":"POL_046","question":"The total number of states in India as of 2026 is:","options":["28","29","30","31"],"answer":0,"explanation":"India has 28 states and 8 Union Territories as of 2026.","difficulty":"easy","topic":"political_science","source":"Indian_Polity"},
    {"id":"POL_047","question":"Which Schedule of the Constitution deals with allocation of seats in Rajya Sabha?","options":["Third Schedule","Fourth Schedule","Fifth Schedule","Sixth Schedule"],"answer":1,"explanation":"Fourth Schedule deals with allocation of seats in Rajya Sabha to states and UTs.","difficulty":"hard","topic":"political_science","source":"Indian_Constitution"},
    {"id":"POL_048","question":"CAA (Citizenship Amendment Act) was enacted in:","options":["2017","2019","2021","2023"],"answer":1,"explanation":"CAA was enacted on 12 December 2019. Its rules were notified on 11 March 2024 making it operational.","difficulty":"medium","topic":"political_science","source":"Indian_Polity"},
    {"id":"POL_049","question":"Under Article 370, special status was earlier given to:","options":["Punjab","Himachal Pradesh","Jammu & Kashmir","Rajasthan"],"answer":2,"explanation":"Article 370 gave special status to J&K. It was abrogated on 5 August 2019 and J&K was reorganized into two UTs.","difficulty":"easy","topic":"political_science","source":"Indian_Constitution"},
    {"id":"POL_050","question":"The Competition Commission of India (CCI) was established under which Act?","options":["Companies Act 2013","FEMA 1999","Competition Act 2002","Consumer Protection Act 2019"],"answer":2,"explanation":"CCI was established under the Competition Act 2002 to prevent anti-competitive practices in the market.","difficulty":"medium","topic":"political_science","source":"Indian_Law"},
]

# ========================================================
# 5. POST HARVEST — Latest Technology 2025 (10 questions)
# ========================================================
post_harvest_2026 = [
    {"id":"PHT_061","question":"APEDA promotes export of which category of products?","options":["Only cereals","Agricultural and processed food products","Only textiles","Only minerals"],"answer":1,"explanation":"APEDA promotes export of agricultural and processed food products including fruits, vegetables, meat, dairy, etc.","difficulty":"easy","topic":"post_harvest","source":"APEDA_2025"},
    {"id":"PHT_062","question":"Cold chain infrastructure in India for horticulture products is strengthened under:","options":["Digital India","MIDH and PMKSY","Swachh Bharat","Make in India"],"answer":1,"explanation":"Cold chain infrastructure is supported under MIDH and Pradhan Mantri Kisan Sampada Yojana (PMKSY) for post-harvest management.","difficulty":"medium","topic":"post_harvest","source":"MIDH_2025"},
    {"id":"PHT_063","question":"PLI scheme for food processing was launched to:","options":["Reduce food production","Boost domestic food processing manufacturing and export","Import more food","Close small units"],"answer":1,"explanation":"PLI scheme provides incentives to boost domestic food processing manufacturing and exports.","difficulty":"easy","topic":"post_harvest","source":"PLI_2025"},
    {"id":"PHT_064","question":"GI tag for agricultural products protects:","options":["Patents of companies","Products with specific geographical origin having unique qualities","Individual trademarks","International brands"],"answer":1,"explanation":"GI tag indicates products originating from a specific geographical region with qualities attributable to that origin.","difficulty":"easy","topic":"post_harvest","source":"GI_Tag"},
    {"id":"PHT_065","question":"Under MIS 2025, PDP (Price Differential Payment) was introduced for:","options":["Only wheat","TOP crops (Tomato, Onion, Potato)","Only rice","Only sugarcane"],"answer":1,"explanation":"MIS 2025 added PDP for TOP crops to protect farmers from price crashes during bumper harvests.","difficulty":"medium","topic":"post_harvest","source":"MIS_2025"},
    {"id":"PHT_066","question":"Mega Food Parks scheme aims to provide:","options":["Free food to all","Modern food processing infrastructure in clusters","Eliminate small food businesses","Import processed food"],"answer":1,"explanation":"Mega Food Parks provide modern infrastructure for food processing with collection, processing, and distribution facilities.","difficulty":"easy","topic":"post_harvest","source":"Food_Processing_2025"},
    {"id":"PHT_067","question":"India aims to increase food processing sector to what % of agricultural output by 2025-26?","options":["15%","25%","35%","50%"],"answer":1,"explanation":"India aims to increase the level of food processing from ~10% to 25% and double agricultural exports through various schemes.","difficulty":"medium","topic":"post_harvest","source":"Food_Processing_2025"},
    {"id":"PHT_068","question":"'One District One Product' helps in post-harvest value addition by:","options":["Ignoring local products","Promoting district-specific products for processing and marketing","Centralizing all production","Banning exports"],"answer":1,"explanation":"ODOP identifies unique products from each district for processing, marketing, and export promotion including post-harvest value addition.","difficulty":"easy","topic":"post_harvest","source":"ODOP_2025"},
    {"id":"PHT_069","question":"Drone technology in agriculture is used for which post-harvest activity?","options":["Only entertainment","Crop monitoring, yield estimation, and precision spraying","Mining only","Construction"],"answer":1,"explanation":"Drones are used for crop monitoring, mapping, yield estimation, precision spraying, and soil analysis in agriculture.","difficulty":"easy","topic":"post_harvest","source":"Agri_Tech_2025"},
    {"id":"PHT_070","question":"FPOs help in post-harvest management by:","options":["Reducing farmer connections","Collectivizing farmers for better bargaining, market access, and reducing input costs","Eliminating small farmers","Only growing crops"],"answer":1,"explanation":"Farmer Producer Organizations improve bargaining power, market access, and reduce input costs for small/marginal farmers.","difficulty":"easy","topic":"post_harvest","source":"FPO_2025"},
]

# ========================================================
# 6. POMOLOGY — Latest Varieties & Developments (10 questions)
# ========================================================
pomology_2026 = [
    {"id":"POM_126","question":"Which apple variety has been introduced for low-chilling areas (subtropical) in India?","options":["Red Delicious","Anna","Royal Gala","Fuji"],"answer":1,"explanation":"Anna apple requires very low chilling (200-300 hrs) and is suitable for subtropical conditions and low-altitude areas.","difficulty":"hard","topic":"pomology","source":"Pomology_2025"},
    {"id":"POM_127","question":"HP SHIVA Project specifically targets which type of horticulture?","options":["Only temperate","Subtropical horticulture","Only tropical","Desert horticulture"],"answer":1,"explanation":"HP SHIVA Project (Subtropical Horticulture, Irrigation and Value Addition) targets subtropical horticulture in seven districts.","difficulty":"medium","topic":"pomology","source":"HP_Scheme_2025"},
    {"id":"POM_128","question":"High Density Planting (HDP) in apple aims at:","options":["Reducing tree number","Increasing trees per hectare for early and higher yield","Only ornamental purpose","Reducing fruit quality"],"answer":1,"explanation":"HDP involves planting 1500-3000 trees/ha (vs 200-500 in traditional) for early bearing and higher yield per unit area.","difficulty":"medium","topic":"pomology","source":"Pomology_2025"},
    {"id":"POM_129","question":"India's apple production is primarily concentrated in:","options":["Tamil Nadu and Kerala","J&K and Himachal Pradesh","Gujarat and Rajasthan","Maharashtra and Karnataka"],"answer":1,"explanation":"J&K and HP together contribute over 95% of India's apple production, with J&K being the largest producer.","difficulty":"easy","topic":"pomology","source":"Pomology_2025"},
    {"id":"POM_130","question":"GALA group of apple (Royal Gala, Gala Must) is known for:","options":["Very sour taste","Attractive red color, sweet flavor, early season maturity","Cooking only","Very late maturity"],"answer":1,"explanation":"Gala apples are known for sweet flavor, attractive bicolor appearance, and early season maturity (August-September).","difficulty":"medium","topic":"pomology","source":"Pomology_2025"},
    {"id":"POM_131","question":"Kiwifruit cultivation in India is expanding primarily in:","options":["Rajasthan","Himachal Pradesh, Arunachal Pradesh, Meghalaya","Gujarat","Tamil Nadu"],"answer":1,"explanation":"Kiwifruit grows well in temperate/sub-temperate regions and is expanding in HP, Arunachal, Meghalaya, Nagaland, and Mizoram.","difficulty":"medium","topic":"pomology","source":"Pomology_2025"},
    {"id":"POM_132","question":"Avocado cultivation in India is gaining momentum in which regions?","options":["Desert areas only","Humid tropics and parts of NE India, Tamil Nadu, and Karnataka","Arctic regions","Only Himachal Pradesh"],"answer":1,"explanation":"Avocado is being recently promoted in humid tropics — parts of NE India, Tamil Nadu, Karnataka, and Kerala.","difficulty":"medium","topic":"pomology","source":"Pomology_2025"},
    {"id":"POM_133","question":"Super-intensive planting system in apple uses rootstock:","options":["Seedling rootstock","M9, M9T337 or their clones","MM106","MM111"],"answer":1,"explanation":"Super-intensive (HDP) apple orchards use dwarfing rootstocks like M9, M9T337 for high density and early production.","difficulty":"hard","topic":"pomology","source":"Pomology_2025"},
    {"id":"POM_134","question":"Dragon fruit (Pitaya) cultivation is being promoted in India under:","options":["Only private initiatives","MIDH and state horticulture missions","No government support","Only research stations"],"answer":1,"explanation":"Dragon fruit cultivation is promoted under MIDH with area expansion subsidies given the growing demand and export potential.","difficulty":"medium","topic":"pomology","source":"MIDH_2025"},
    {"id":"POM_135","question":"Net Income Mission for Apple Orchards in HP focuses on:","options":["Reducing apple production","Replacing old orchards with high-density plantations","Only exporting apples","Stopping horticulture"],"answer":1,"explanation":"The mission focuses on replacing old, unproductive orchards with high-density plantations using modern rootstocks for higher returns.","difficulty":"medium","topic":"pomology","source":"HP_Scheme_2025"},
]

# ========================================================
# 7. OLERICULTURE — Latest Developments (5 questions)
# ========================================================
oleri_2026 = [
    {"id":"OLE_111","question":"India's vegetable production in 2024-25 is approximately:","options":["180 MT","195 MT","215.68 MT","230 MT"],"answer":2,"explanation":"India's vegetable output estimated at 215.68 million tonnes in 2024-25, growing by 4.09%.","difficulty":"medium","topic":"olericulture","source":"Horticulture_2025"},
    {"id":"OLE_112","question":"Protected cultivation of vegetables (polyhouse/shade net) is promoted under:","options":["Only private investment","MIDH with subsidy support","No government scheme","Only MGNREGA"],"answer":1,"explanation":"MIDH provides subsidy support for protected cultivation structures like polyhouses and shade net houses for vegetables.","difficulty":"easy","topic":"olericulture","source":"MIDH_2025"},
    {"id":"OLE_113","question":"TOP (Tomato, Onion, Potato) scheme under MIS 2025 focuses on:","options":["Exporting all production","Price stabilization through Market Intervention and PDP","Banning cultivation","Only research"],"answer":1,"explanation":"TOP scheme stabilizes prices of tomato, onion, potato through market intervention and new Price Differential Payment mechanism.","difficulty":"medium","topic":"olericulture","source":"MIS_2025"},
    {"id":"OLE_114","question":"Vertical farming and soilless cultivation for vegetables is categorized under:","options":["Traditional farming only","Precision/modern horticulture under MIDH","Animal husbandry","Forestry"],"answer":1,"explanation":"Vertical/soilless cultivation (hydroponics, aeroponics) is promoted under modern horticulture initiatives within MIDH.","difficulty":"medium","topic":"olericulture","source":"MIDH_2025"},
    {"id":"OLE_115","question":"Biofortified vegetable varieties (iron/zinc enriched) are developed by:","options":["Private companies only","ICAR institutes like IIVR Varanasi","Foreign agencies only","No one develops them"],"answer":1,"explanation":"ICAR-IIVR Varanasi and other ICAR institutes develop biofortified vegetable varieties enriched with iron, zinc, and vitamins.","difficulty":"medium","topic":"olericulture","source":"ICAR_2025"},
]

# ========================================================
# 8. FLORICULTURE — Latest Developments (5 questions)
# ========================================================
flori_2026 = [
    {"id":"FLO_071","question":"India's global rank in floriculture area is:","options":["1st","2nd","3rd","5th"],"answer":1,"explanation":"India ranks 2nd globally in floriculture area after China, covering approximately 3.16 lakh hectares.","difficulty":"medium","topic":"floriculture","source":"Floriculture_2025"},
    {"id":"FLO_072","question":"Protected cultivation of flowers in India is highest in:","options":["Tamil Nadu and Karnataka","Maharashtra and HP","Rajasthan","Gujarat"],"answer":0,"explanation":"Protected cultivation of flowers (polyhouse roses, gerbera, carnations) is most extensive in Tamil Nadu and Karnataka.","difficulty":"medium","topic":"floriculture","source":"Floriculture_2025"},
    {"id":"FLO_073","question":"India's flower export potential is primarily in:","options":["Only marigold","Rose, orchid, gladiolus, tuberose, and cut flowers","Only jasmine","Only chrysanthemum"],"answer":1,"explanation":"India exports mainly roses, orchids, gladiolus, tuberose, and various cut flowers to international markets.","difficulty":"easy","topic":"floriculture","source":"Floriculture_2025"},
    {"id":"FLO_074","question":"E-NAM integration with flower auctions helps in:","options":["Reducing flower production","Transparent price discovery and wider market access for flower growers","Only local selling","Closing markets"],"answer":1,"explanation":"e-NAM integration enables transparent price discovery, wider market access, and reduces middlemen for flower growers.","difficulty":"medium","topic":"floriculture","source":"e-NAM_2025"},
    {"id":"FLO_075","question":"Which flower is being promoted for its essential oil and aromatic properties under MIDH?","options":["Rose and lavender","Only marigold","Only sunflower","Only lotus"],"answer":0,"explanation":"Rose and lavender are promoted for essential oil extraction under MIDH's aromatic plants component alongside traditional flowers.","difficulty":"medium","topic":"floriculture","source":"MIDH_2025"},
]

# ========================================================
# RUN ALL ADDITIONS
# ========================================================
print("Adding latest 2025-2026 current affairs questions (Part 4)...")
append_questions(os.path.join(BASE, "data/general/current_affairs.json"), current_affairs_2026)
append_questions(os.path.join(BASE, "data/general/hp_gk.json"), hp_gk_2026)
append_questions(os.path.join(BASE, "data/general/political_science.json"), polsci_2026)
append_questions(os.path.join(BASE, "data/horticulture/general_horticulture.json"), gen_hort_2026)
append_questions(os.path.join(BASE, "data/horticulture/post_harvest.json"), post_harvest_2026)
append_questions(os.path.join(BASE, "data/horticulture/pomology.json"), pomology_2026)
append_questions(os.path.join(BASE, "data/horticulture/olericulture.json"), oleri_2026)
append_questions(os.path.join(BASE, "data/horticulture/floriculture.json"), flori_2026)
print("\nPart 4 complete! Latest 2025-2026 questions added across all sections.")
